
name: Testing workflow

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: List all files
        run: ls

      - name: Install Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      
      - name: Install connector 
        run: pip install snowflake-connector-python --upgrade

      - name: Install pandas 
        run: pip install pandas --upgrade

      - name: Install pandas snowflake
        run: pip install snowflake-connector-python[pandas] --upgrade
            
      - name: Run dataframe  
        env:
          SF_ACCOUNT: ${{SECRETS.SF_ACCOUNT}}
          SF_PASSWORD: ${{secrets.SF_PASSWORD}}
          SF_USERNAME: ${{secrets.SF_USERNAME}}
        run: python testes/connection.py        

      - name: Run null tests  
        env:
          SF_ACCOUNT: ${{SECRETS.SF_ACCOUNT}}
          SF_PASSWORD: ${{secrets.SF_PASSWORD}}
          SF_USERNAME: ${{secrets.SF_USERNAME}}
        run: python testes/is_null.py

      - name: Run row tests
        env:
          SF_ACCOUNT: ${{SECRETS.SF_ACCOUNT}}
          SF_PASSWORD: ${{secrets.SF_PASSWORD}}
          SF_USERNAME: ${{secrets.SF_USERNAME}}
        run: python testes/row_number.py

      - name: run col tests
        env:
          SF_ACCOUNT: ${{SECRETS.SF_ACCOUNT}}
          SF_PASSWORD: ${{secrets.SF_PASSWORD}}
          SF_USERNAME: ${{secrets.SF_USERNAME}}      
        run: python testes/col_number.py