name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'dev/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.7.x

      - name: Run Python Script
        run: python V1.1.1__connection_python.py
        env:
          SF_ACCOUNT: ${{ env.SF_ACCOUNT}} 
          SF_USERNAME: ${{ env.SF_USERNAME}} 
          SNOWFLAKE_PASSWORD: ${{ env.SNOWFLAKE_PASSWORD }} 